/* eslint-disable @typescript-eslint/no-explicit-any */
export interface IAccount {
  item_id: number;
  item_state: string;
  category_id: number;
  published_date: number;
  title: string;
  description: string;
  price: number;
  update_stat_date: number;
  refreshed_date: number;
  edit_date: number;
  view_count: number;
  is_sticky: number;
  item_origin: string;
  extended_guarantee: number;
  nsb: number;
  allow_ask_discount: number;
  title_en: string;
  description_en: string;
  email_type: string;
  email_provider: string;
  item_domain: string;
  resale_item_origin: string;
  steam_item_id: number;
  steam_country: string;
  steam_register_date: number;
  steam_last_activity: number;
  steam_full_games: {
    list: {
      [key: string]: {
        appid: number;
        playtime_forever: number;
        internal_game_id: number;
        abbr: string;
        title: string;
        parentGameId: number;
        img: string;
      };
    };
    total: number;
  };
  steam_community_ban: number;
  steam_bans: string;
  steam_cs2_profile_rank: number;
  steam_balance: string;
  steam_cs2_rank_id: number;
  steam_is_limited: number;
  steam_level: number;
  steam_friend_count: number;
  steam_cs2_last_activity: number;
  steam_dota2_solo_mmr: number;
  steam_cs2_ban_date: number;
  steam_converted_balance: number;
  steam_cards_count: number;
  steam_cards_games: number;
  steam_pubg_inv_value: number;
  steam_cs2_inv_value: number;
  steam_dota2_inv_value: number;
  steam_tf2_inv_value: number;
  steam_rust_inv_value: number;
  steam_cs2_wingman_rank_id: number;
  steam_game_count: number;
  steam_steam_inv_value: number;
  steam_inv_value: number;
  steam_cs2_win_count: number;
  steam_dota2_game_count: number;
  steam_dota2_lose_count: number;
  steam_dota2_win_count: number;
  steam_hours_played_recently: string;
  steam_has_faceit: boolean | null;
  steam_faceit_cs2_level: number;
  steam_faceit_csgo_level: number | null;
  steam_points: number;
  steam_last_transaction_date: number;
  steam_relevant_game_count: number;
  steam_gift_count: number;
  steam_limit_spent: string;
  steam_dota2_behavior: number;
  steam_mfa: number;
  steam_market: number;
  steam_market_restrictions: number;
  steam_market_ban_end_date: number;
  steam_unturned_inv_value: number;
  steam_cs2_last_launched: number;
  steam_kf2_inv_value: number;
  steam_dst_inv_value: number;
  steam_cs2_premier_elo: number;
  steam_has_activated_keys: number;
  steam_cs2_ban_type: number;
  steam_rust_kill_player: number;
  steam_rust_deaths: number;
  steam_total_gifts_rub: number;
  steam_total_refunds_rub: number;
  steam_total_ingame_rub: number;
  steam_total_games_rub: number;
  steam_total_purchased_rub: number;
  steam_dota2_last_match_date: number;
  feedback_data: string;
  isIgnored: boolean;
  priceWithSellerFee: number;
  guarantee: {
    duration: number;
    class: string;
    durationPhrase: string;
    endDate: number | null;
    active: number | null;
    cancelled: number | null;
    remainingTime: number | null;
  };
  canViewLoginData: boolean;
  canUpdateItemStats: boolean;
  canReportItem: boolean;
  canViewEmailLoginData: boolean;
  copyFormatData: {
    title_link: string;
  };
  showGetEmailCodeButton: boolean;
  canOpenItem: boolean;
  canCloseItem: boolean;
  canEditItem: boolean;
  canDeleteItem: boolean;
  canStickItem: boolean;
  canUnstickItem: boolean;
  bumpSettings: {
    canBumpItem: boolean;
    canBumpItemGlobally: boolean;
    shortErrorPhrase: string | null;
    errorPhrase: string | null;
  };
  isPersonalAccount: boolean;
  canBumpItem: boolean;
  canBuyItem: boolean;
  rub_price: number;
  price_currency: string;
  priceWithSellerFeeLabel: string;
  canValidateAccount: boolean;
  canResellItemAfterPurchase: boolean;
  steamData: {
    steam_ban_type_id: number[];
  };
  removed_games: {
    [key: string]: {
      appid: number;
      playtime_forever: number;
    };
  };
  steamRelevantGameCount: number;
  isSmallExf: boolean;
  account_last_activity: number;
  hasCs2: boolean;
  hasDota2: boolean;
  hasPubg: boolean;
  hasTf2: boolean;
  hasRust: boolean;
  steam_cs2_ban_date_active: boolean;
  dota2CalibrationWarning: boolean;
  displayConvertedBalance: boolean;
  inventoryValue: {
    [key: string]: {
      title: string;
      value: number;
      column: string;
    };
  };
  steamCs2Medals: {
    title: string;
    medal_id: number;
    image_url: string;
  }[];
  steamGifts: any[];
  cs2RankExpired: boolean;
  steamDota2WinRate: number;
  steamTransactions: any[];
  hasPossibleBanInDota2: boolean;
  chineseAccount: boolean;
  cs2MapsRanks: {
    item_id: number;
    rank_id: number;
    map_id: number;
    map_win: number;
    map_name: string;
  }[];
  cs2PremierElo: any[];
  steamLifetimeTradeBan: boolean;
  canViewAccountLink: boolean;
  accountLinks: {
    link: string;
    text: string;
    iconClass: string;
  }[];
  accountLink: string;
  emailLoginUrl: string;
  canChangePassword: boolean;
  uniqueKeyExists: boolean;
  itemOriginPhrase: string;
  sold_items_category_count: number;
  restore_items_category_count: number;
  tags: any[];
  note_text: string | null;
  hasPendingAutoBuy: boolean;
  descriptionHtml: string;
  descriptionEnHtml: string;
  descriptionPlain: string;
  descriptionEnPlain: string;
  seller: {
    user_id: number;
    sold_items_count: number;
    active_items_count: number;
    restore_data: string;
    username: string;
    avatar_date: number;
    is_banned: number;
    display_style_group_id: number;
    restore_percents: number;
  };
}
