import React from 'react';
import Item from './Item';

function CategoryList() {
  // https://api.lzt.market/category

  const categories = React.useMemo(
    () => [
      {
        category_id: 1,
        sub_category_id: 1,
        category_order: 10,
        category_title: 'Steam',
        category_name: 'steam',
        category_url: 'steam',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты steam с %s, а так же у нас есть продажа аккаунтов стим с %s.',
        category_login_url: 'https://steamcommunity.com/login/home/',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 1,
        has_account_link: 1,
        require_temp_email: 1,
        recovery_link:
          'https://help.steampowered.com/en/wizard/HelpWithLoginInfo?accountsearch=1',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 1,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 100,
        category_prefix_id: 105,
        view_items: 1,
        autobuy_price_coefficient: 1.5,
        proxy_error: 0
      },
      {
        category_id: 9,
        sub_category_id: 1,
        category_order: 20,
        category_title: 'Fortnite',
        category_name: 'fortnite',
        category_url: 'fortnite',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести аккаунты фортнайт по низкой цене со скинами и pve',
        category_login_url:
          'https://www.epicgames.com/id/login/epic?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3FproductName%3Dfortnite%26lang%3Dru',
        add_item_available: 1,
        mass_upload_item_available: 0,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: 'https://www.epicgames.com/id/login/forgot-password',
        check_button_enabled: 0,
        checker_enabled: 1,
        checker_partially_disabled: 1,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 1,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 1,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 1,
        cookies: 'required',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 1,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 112,
        view_items: 1,
        autobuy_price_coefficient: 2,
        proxy_error: 0
      },
      {
        category_id: 17,
        sub_category_id: 1,
        category_order: 40,
        category_title:
          'miHoYo: Genshin Impact, Honkai Star Rail, Zenless Zone Zero',
        category_name: 'mihoyo',
        category_url: 'mihoyo',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты геншин импакт, хонкай стар рейл, зенлесс зон зеро с легендарными персонажами, много созвездий и легендарных оружий',
        category_login_url:
          'https://account.mihoyo.com/?lang=en#/account/safetySettings',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 203,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 13,
        sub_category_id: 1,
        category_order: 50,
        category_title: 'Riot Games',
        category_name: 'riot',
        category_url: 'riot',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести качественные аккаунты валорант бета без привязок по низким ценам',
        category_login_url: 'https://account.riotgames.com/',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 1,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'username',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 504,
        view_items: 1,
        autobuy_price_coefficient: 1.5,
        proxy_error: 0
      },
      {
        category_id: 24,
        sub_category_id: 1,
        category_order: 60,
        category_title: 'Telegram',
        category_name: 'telegram',
        category_url: 'telegram',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести аккаунт Telegram оптом, с отлежкой, в комплекте идет tdata, широкий выбор стран: Россия, Украина, США, а также авторег телеграм аккаунты',
        category_login_url: '',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: 'Telegram',
        category_h1_html_en: 'Telegram',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 0,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 90,
        buy_without_validation: 1,
        max_invalid_upload_tries: 100,
        category_prefix_id: 499,
        view_items: 1,
        autobuy_price_coefficient: 2,
        proxy_error: 0
      },
      {
        category_id: 15,
        sub_category_id: 1,
        category_order: 70,
        category_title: 'Supercell',
        category_name: 'supercell',
        category_url: 'supercell',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести аккаунт Brawl Stars, Clash of Clans или Clash Royale. Есть аккаунты с дорогими бравлерами, есть дешевые и прокаченные акки',
        category_login_url: '',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 0,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 1,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 117,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 3,
        sub_category_id: 1,
        category_order: 80,
        category_title: 'Origin (EA)',
        category_name: 'ea',
        category_url: 'origin',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты Origin Орижин (Ea) с ФИФА FIFA FC 24, Батлфилд или батлой Battlefield 2042, и нид фор спид, стар варс. Кроме того, у нас есть продажа аккаунтов Apex Legends (апекс легендс) с реликвиями и редкими скинами по низким ценам',
        category_login_url: 'https://www.origin.com/rus/ru-ru/store',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 1,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 108,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 14,
        sub_category_id: 1,
        category_order: 90,
        category_title: 'World of Tanks',
        category_name: 'wot',
        category_url: 'world-of-tanks',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты ворлд оф тэнкс с золотом, много боев, без привязок по очень низким ценам',
        category_login_url: 'https://ru.wargaming.net/id/signin/',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 100,
        category_prefix_id: 116,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 16,
        sub_category_id: 1,
        category_order: 95,
        category_title: 'World of Tanks Blitz',
        category_name: 'wot',
        category_url: 'wot-blitz',
        category_description_html:
          'Аккаунты World of Tanks Blitz без привязки с золотом и техникой',
        category_login_url: 'https://ru.wargaming.net/id/signin/',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 100,
        category_prefix_id: 116,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 12,
        sub_category_id: 1,
        category_order: 99,
        category_title: 'Epic Games',
        category_name: 'eg',
        category_url: 'epicgames',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести качественные аккаунты epic games по низким ценам, а также с игрой Metro Exodus, RDR 2, World War Z, Borderlands 3',
        category_login_url:
          'https://www.epicgames.com/id/login/epic?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Faccount%2Fpersonal%3FproductName%3Dfortnite%26lang%3Dru',
        add_item_available: 1,
        mass_upload_item_available: 0,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: 'https://www.epicgames.com/id/login/forgot-password',
        check_button_enabled: 0,
        checker_enabled: 1,
        checker_partially_disabled: 1,
        support_personal_proxy: 0,
        support_email_login_data: 1,
        require_email_login_data: 1,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 1,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 1,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 115,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 28,
        sub_category_id: 1,
        category_order: 100,
        category_title: 'Minecraft',
        category_name: 'minecraft',
        category_url: 'minecraft',
        category_description_html: 'minecraft',
        category_login_url: '',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 515,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 30,
        sub_category_id: 1,
        category_order: 100,
        category_title: 'Подписки',
        category_name: 'gifts',
        category_url: 'gifts',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести Telegram Premium и Discord Nitro подарочными ссылками на 1 месяц, 3 месяца, 6 месяцев, 12 месяцев',
        category_login_url: '',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en:
          'Our site offers a unique opportunity to purchase Telegram Premium and Discord Nitro gift links for 1 month, 3 months, 6 months, 12 months',
        category_h1_html_en: 'Gifts',
        account_price_min: 1,
        require_video_recording: 0,
        require_eld_for_native_accs: 0,
        can_be_resold: 0,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 0,
        buy_without_validation: 0,
        max_invalid_upload_tries: 30,
        category_prefix_id: 621,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 18,
        sub_category_id: 1,
        category_order: 110,
        category_title: 'Escape from Tarkov',
        category_name: 'tarkov',
        category_url: 'escape-from-tarkov',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести качественные аккаунты Escape From Tarkov с валютой и прокаченным персонажем.',
        category_login_url: 'https://www.escapefromtarkov.com/login',
        add_item_available: 1,
        mass_upload_item_available: 0,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 1,
        require_email_login_data: 1,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 1,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 233,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 7,
        sub_category_id: 1,
        category_order: 120,
        category_title: 'Social Club',
        category_name: 'socialclub',
        category_url: 'socialclub',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты сошл клаб с гта 5 без бана и привязки.',
        category_login_url:
          'https://signin.rockstargames.com/signin/user-form?cid=socialclub',
        add_item_available: 1,
        mass_upload_item_available: 0,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 1,
        recovery_link: '',
        check_button_enabled: 0,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 1,
        require_eld_for_native_accs: 0,
        can_be_resold: 1,
        support_temp_email: 1,
        cookies: 'required',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 111,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 5,
        sub_category_id: 1,
        category_order: 130,
        category_title: 'Uplay',
        category_name: 'uplay',
        category_url: 'uplay',
        category_description_html:
          "На нашем сайте предоставляется уникальная возможность купить аккаунты assassin's creed origins, с the crew а так же у нас есть продажа аккаунтов uplay с far cry",
        category_login_url: 'https://account.ubisoft.com/',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 110,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 27,
        sub_category_id: 1,
        category_order: 140,
        category_title: 'War Thunder',
        category_name: 'wt',
        category_url: 'war-thunder',
        category_description_html: '',
        category_login_url: 'https://login.gaijin.net/ru/',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 510,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 22,
        sub_category_id: 1,
        category_order: 150,
        category_title: 'Discord',
        category_name: 'discord',
        category_url: 'discord',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести дискорд токены по низкой цене, проспам, чистые токены, с биллингом',
        category_login_url: '',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: 'Discord',
        category_h1_html_en: 'Discord',
        account_price_min: 1,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 100,
        category_prefix_id: 444,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 20,
        sub_category_id: 1,
        category_order: 170,
        category_title: 'TikTok',
        category_name: 'tiktok',
        category_url: 'tiktok',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты тикток с подписчиками, лайками, а так же у нас есть продажа аккаунтов тикток для рекламы и с отлежкой.',
        category_login_url: 'https://www.tiktok.com/login',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 0,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '123',
        account_price_min: 1,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'required',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 364,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 10,
        sub_category_id: 1,
        category_order: 180,
        category_title: 'Instagram',
        category_name: 'instagram',
        category_url: 'instagram',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести качественные аккаунты instagram по низкой цене с подписчиками, а также пустые, автореги, брут, с большим количеством публикаций',
        category_login_url:
          'https://www.instagram.com/accounts/login/?source=auth_switcher',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 1,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'available',
        login_type: 'username',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 113,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 11,
        sub_category_id: 1,
        category_order: 190,
        category_title: 'Battle.net',
        category_name: 'battlenet',
        category_url: 'battlenet',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести качественные аккаунты батл нет за 10 рублей, а также с овервотчем',
        category_login_url: 'https://www.blizzard.com/login',
        add_item_available: 1,
        mass_upload_item_available: 0,
        has_guarantee: 1,
        has_account_link: 1,
        require_temp_email: 1,
        recovery_link:
          'https://eu.battle.net/account/recovery/en-us/identify-account.html?requestType=PASSWORD_RESET',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 1,
        cookies: 'none',
        login_type: 'email',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 114,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 19,
        sub_category_id: 1,
        category_order: 200,
        category_title: 'VPN',
        category_name: 'vpn',
        category_url: 'vpn',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты впн сервисов, такие как Vypr VPN, Surfshark VPN, IpVanish, Windscribe VPN Pro, а также vpn аккаунты ZenMate, TunnelBear VPN\r\n',
        category_login_url: '1',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 0,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 1,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 351,
        view_items: 1,
        autobuy_price_coefficient: 0.25,
        proxy_error: 0
      },
      {
        category_id: 23,
        sub_category_id: 1,
        category_order: 210,
        category_title: 'Онлайн-кинотеатры',
        category_name: 'cinema',
        category_url: 'cinema',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность приобрести аккаунт онлайн кинотеатра: окко, иви, кинопоиск, мегого и другие',
        category_login_url: '',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 1,
        require_video_recording: 0,
        require_eld_for_native_accs: 0,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 1,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 477,
        view_items: 1,
        autobuy_price_coefficient: 0.25,
        proxy_error: 0
      },
      {
        category_id: 31,
        sub_category_id: 1,
        category_order: 210,
        category_title: 'Roblox',
        category_name: 'roblox',
        category_url: 'roblox',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты roblox с robux, а так-же аккаунты роблокс с робуксами.',
        category_login_url: 'https://www.roblox.com/login',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 1,
        require_temp_email: 0,
        recovery_link:
          'https://www.roblox.com/login/forgot-password-or-username',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: 'Roblox',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 1,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 627,
        view_items: 1,
        autobuy_price_coefficient: 1,
        proxy_error: 0
      },
      {
        category_id: 26,
        sub_category_id: 1,
        category_order: 220,
        category_title: 'Spotify',
        category_name: 'spotify',
        category_url: 'spotify',
        category_description_html: '',
        category_login_url:
          'https://www.spotify.com/int/login/?continue=https%3A%2F%2Fopen.spotify.com%2F__noul__%3Fl2l%3D1%26nd%3D1',
        add_item_available: 1,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 1,
        support_email_login_data: 1,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: 'Spotify',
        account_price_min: 5,
        require_video_recording: 0,
        require_eld_for_native_accs: 0,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 508,
        view_items: 1,
        autobuy_price_coefficient: 0.5,
        proxy_error: 0
      },
      {
        category_id: 4,
        sub_category_id: 1,
        category_order: 230,
        category_title: 'Warface',
        category_name: 'wf',
        category_url: 'warface',
        category_description_html:
          'На нашем сайте предоставляется уникальная возможность купить аккаунты warface без привязки, с донатом а так же у нас есть продажа аккаунтов варфейс альфа, чарли без обмана.',
        category_login_url: 'https://wf.mail.ru/',
        add_item_available: 4,
        mass_upload_item_available: 1,
        has_guarantee: 0,
        has_account_link: 0,
        require_temp_email: 0,
        recovery_link: '',
        check_button_enabled: 1,
        checker_enabled: 1,
        checker_partially_disabled: 0,
        support_personal_proxy: 0,
        support_email_login_data: 0,
        require_email_login_data: 0,
        display_in_list: 1,
        category_description_html_en: '',
        category_h1_html_en: '',
        account_price_min: 5,
        require_video_recording: 1,
        require_eld_for_native_accs: 0,
        can_be_resold: 1,
        support_temp_email: 0,
        cookies: 'none',
        login_type: 'any',
        guest_hidden: 0,
        available_temp_email: 0,
        resale_duration_limit_days: 30,
        buy_without_validation: 1,
        max_invalid_upload_tries: 30,
        category_prefix_id: 109,
        view_items: 1,
        autobuy_price_coefficient: 0.25,
        proxy_error: 0
      }
    ],
    []
  );

  return (
    <div className='flex flex-col gap-4'>
      <h3 className='text-lg font-normal text-secondaryCustoms'>
        Select a category first
      </h3>
      <div className='flex items-center gap-[18px] lg:gap-4 flex-wrap'>
        {categories.map((category) => (
          <Item key={category?.category_id} category={category} />
        ))}
      </div>
    </div>
  );
}

export default CategoryList;
